### ISSUE TITLE
Internal worker not working as expecte

### ISSUE THREAD

**Issue by Inokinoki** [Giskard-AI/giskard#1376]
### Issue Type

Bug

### Source

source

### Giskard Library Version

2.0.14b

### Giskard Server Version

2.0.14b

### Current Behaviour?

```shell
Internal worker behaviours
```

### Standalone code OR list down the steps to reproduce the issue

```shell
Show as following
```

**Comment by Inokinoki** [comment]
Running test without slicing function is OK:
<img width="840" alt="image" src="https://github.com/Giskard-AI/giskard/assets/8311300/d097c877-6ef9-4717-84cb-b6214bc1eb26">

With slicing function:
<img width="1086" alt="image" src="https://github.com/Giskard-AI/giskard/assets/8311300/fbd8bfb3-8409-408f-aaca-ac32e2b393b0">

```
could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:giskard.core.core.DatasetProcessFunctionMeta'
  in "/**/giskard-home/projects/global/slices/5fa8728c-dc72-55f4-bb36-222baf9e6c2a/meta.yaml", line 1, column 1
```

**Comment by Inokinoki** [comment]
Running test giving the similar results

```
2023-09-04 09:05:05,647 INFO Casting dataframe columns from {'PassengerId': 'int64', 'Pclass': 'int64', 'Name': 'object', 'Sex': 'object', 'Age': 'float64', 'SibSp': 'int64', 'Parch': 'int64', 'Fare': 'float64', 'Embarked': 'object', 'Survived': 'object'} to {'Age': 'float64', 'Embarked': 'object', 'Fare': 'float64', 'Name': 'object', 'Parch': 'int64', 'PassengerId': 'int64', 'Pclass': 'int64', 'Sex': 'object', 'SibSp': 'int64', 'Survived': 'object'}
2023-09-04 09:05:05,653 INFO Your 'pandas.DataFrame' is successfully wrapped by Giskard's 'Dataset' wrapper class.
2023-09-04 09:05:05,655 ERROR An error occurred during the test suite execution: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:giskard.core.core.DatasetProcessFunctionMeta'
  in "/Users/inoki/giskard-home/projects/global/slices/55c05211-7d49-58b4-a183-a16ef3201825/meta.yaml", line 1, column 1
Traceback (most recent call last):
  File "/Users/inoki/Builds/giskard/python-client/giskard/ml_worker/websocket/listener.py", line 507, in run_test_suite
    tests = [
  File "/Users/inoki/Builds/giskard/python-client/giskard/ml_worker/websocket/listener.py", line 510, in <listcomp>
    "arguments": parse_function_arguments(ml_worker, t.arguments),
  File "/Users/inoki/Builds/giskard/python-client/giskard/ml_worker/websocket/utils.py", line 178, in parse_function_arguments
    arguments[arg.name] = SlicingFunction.download(arg.slicingFunction.id, ml_worker.client, None)(
  File "/Users/inoki/Builds/giskard/python-client/giskard/ml_worker/core/savable.py", line 119, in download
    meta = cls._load_meta_locally(local_dir, uuid)
  File "/Users/inoki/Builds/giskard/python-client/giskard/ml_worker/core/savable.py", line 148, in _load_meta_locally
    return super()._load_meta_locally(local_dir, uuid)
  File "/Users/inoki/Builds/giskard/python-client/giskard/ml_worker/core/savable.py", line 67, in _load_meta_locally
    return cls._get_meta_class(**yaml.load(f, Loader=yaml.FullLoader))
  File "/Users/inoki/Builds/giskard/python-client/.venv/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/Users/inoki/Builds/giskard/python-client/.venv/lib/python3.9/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/Users/inoki/Builds/giskard/python-client/.venv/lib/python3.9/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/Users/inoki/Builds/giskard/python-client/.venv/lib/python3.9/site-packages/yaml/constructor.py", line 101, in construct_object
    data = constructor(self, node)
  File "/Users/inoki/Builds/giskard/python-client/.venv/lib/python3.9/site-packages/yaml/constructor.py", line 428, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:giskard.core.core.DatasetProcessFunctionMeta'
  in "/Users/inoki/giskard-home/projects/global/slices/55c05211-7d49-58b4-a183-a16ef3201825/meta.yaml", line 1, column 1
```

**Comment by Inokinoki** [comment]
To create debug session, working well with creating from catalog:
<img width="1278" alt="image" src="https://github.com/Giskard-AI/giskard/assets/8311300/10a6fced-4dfd-405d-8cfc-00f29bfd4fb6">

Not working with slicing function:
<img width="1278" alt="image" src="https://github.com/Giskard-AI/giskard/assets/8311300/9d685e7c-0ce1-4b77-b6aa-c3f39fb19bdb">

**Comment by Inokinoki** [comment]
Unlocated:
<img width="1278" alt="image" src="https://github.com/Giskard-AI/giskard/assets/8311300/8ad75566-9a8b-49e6-b6da-48876f0b56c9">

**Comment by Inokinoki** [comment]
The amount of test functions is not normal:
<img width="1278" alt="image" src="https://github.com/Giskard-AI/giskard/assets/8311300/7269c480-225a-42ee-bc20-028e680bfdc7">
