### ISSUE TITLE
Checking the prediction_function signature in case of non-pandas df input

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#657]
We currently have:
```
    def upload_model_and_df(
            self,
            prediction_function: Callable[[pd.DataFrame], Iterable[Union[str, float, int]]],
            etc...
```
This hint should do the following (see example below):
```
def greeting(name: str) -> str:
    return 'Hello ' + name

greeting(1.5)
>>>
Traceback (most recent call last):
File "<string>", line 7, in <module>
  File "<string>", line 5, in greeting
TypeError: can only concatenate str (not "float") to str
```
but... giving a `prediction_function` that has a list (instead of pandas) doesn't produce an error:
```
def prediction_function(input: List[int]):
    return input
    

def test_func(prediction_function: Callable[[pd.DataFrame], Iterable[Union[str, float, int]]]):
    print(prediction_function)
    
test_func(prediction_function)
```

This was observed by Etam, that had a problem with the upload due to the fact that the input of their prediction_function wasn't a pandas dataframe

**Comment by rabah-khalek** [comment]
it seems to me a rare case where the user is aware that he should give a pandas.dataframe to give to Giskard, but keeps their prediction_function input as xgb.matrix

It's difficult to make a check other than the one we did here:
```python
    def _validate_model_execution(self, prediction_function, df: pd.DataFrame, model_type,
                                  classification_labels=None, target=None) -> None:
        if target is not None and target in df.columns:
            df = df.drop(target, axis=1)
        try:
            prediction_function(df.head(1))
        except Exception:
            raise ValueError("Invalid prediction_function input.\n"
                             "Please make sure that prediction_function(df.head(1)) does not return an error "
                             "message before uploading in Giskard")
```
If they got here, it means that they passed to `upload_model_and_df` a `pandas.dataframe`
