### ISSUE TITLE
can't upload to "http://dev.giskard.ai" anymore

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#683]
### Issue Type

Bug

### Source

source

### Giskard Library Version

1.7,0

### Giskard Server Version

1.3.0

### OS Platform and Distribution

dev.giskard.ai

### Python version

3.8

### Current Behaviour?

```shell
we used to be able to update to "http://dev.giskard.ai"
```

### Standalone code OR list down the steps to reproduce the issue

```shell
try to upload any project to "http://dev.giskard.ai"
```

### Relevant log output

```shell
Model successfully uploaded to project key 'None' with ID = None. It is available at http://dev.giskard.ai 
Traceback (most recent call last):
  File "Giskard_test.py", line 75, in <module>
    test_suite_id = credit_scoring.list_test_suites()[0]['id']
  File "/Users/rak/Documents/giskard-master/python-client/giskard/client/project.py", line 117, in list_test_suites
    return [{"id": t["id"], "name": t["name"]} for t in res]
  File "/Users/rak/Documents/giskard-master/python-client/giskard/client/project.py", line 117, in <listcomp>
    return [{"id": t["id"], "name": t["name"]} for t in res]
TypeError: string indices must be integers
```
```

**Comment by rabah-khalek** [comment]
Closing as outdated
