### ISSUE TITLE
OSError: [Errno 30] Read-only file system: 'tmp_trainer' - external worker started as deamon

### ISSUE THREAD

**Issue by kevinmessiaen** [Giskard-AI/giskard#723]
### Issue Type

Bug

### Source

docker

### Giskard Library Version

1.7.0

### Giskard Server Version

1.3.2

### OS Platform and Distribution

macOS Ventura 13.2

### Python version

3.8.16

### Installed python packages

transformers==4.26.0

### Current Behaviour?

```shell
When running Giskard as a daemon (-d) option, the error message appears, the error message does not appear when running without -d option
```

### Standalone code OR list down the steps to reproduce the issue

```shell
- Start an external ML worker using `giskard worker start -d`
- Upload `Sentiment_Analysis_for_Twitter_Data` project from giskard-examples
- Inspect the dataset and see the error logs

Then:
- stop the ML worker using `giskard worker stop`
- Start the ML worker using `giskard worker start`
- Inspect the dataset without error
```

### Relevant log output

```shell
2023-02-08 10:45:59,939 pid:13172 MainThread giskard.ml_worker.utils.error_interceptor ERROR    [Errno 30] Read-only file system: 'tmp_trainer'
Traceback (most recent call last):
  File "/Users/kevinmessiaen/.pyenv/versions/3.8.16/lib/python3.8/site-packages/giskard/ml_worker/utils/error_interceptor.py", line 48, in wrapper
    res = await loop.run_in_executor(pool, behavior, request, context)
  File "/Users/kevinmessiaen/.pyenv/versions/3.8.16/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/kevinmessiaen/.pyenv/versions/3.8.16/lib/python3.8/site-packages/giskard/ml_worker/server/ml_worker_service.py", line 224, in runModel
    prediction_results = model.run_predict(dataset)
  File "/Users/kevinmessiaen/.pyenv/versions/3.8.16/lib/python3.8/site-packages/giskard/ml_worker/core/model.py", line 40, in run_predict
    raw_prediction = self.prediction_function(df)
  File "/Users/kevinmessiaen/work/giskard-examples/venv/lib/python3.8/site-packages/giskard/client/project.py", line 437, in <lambda>
    return lambda df: prediction_function(df[feature_names])
  File "/var/folders/nf/w2h_y58n4sxdyjmq4qlwcxym0000gn/T/ipykernel_3030/1249985334.py", line 10, in predict
  File "/Users/kevinmessiaen/.pyenv/versions/3.8.16/lib/python3.8/site-packages/transformers/trainer.py", line 505, in __init__
    os.makedirs(self.args.output_dir, exist_ok=True)
  File "/Users/kevinmessiaen/.pyenv/versions/3.8.16/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: 'tmp_trainer'
```

**Comment by andreybavt** [comment]
fixed in 57a90f0dbc931bb294e56b0c4b2595646e882b43
