### ISSUE TITLE
Cannot set worker.SingleTestResult.passed to False (python3.10)

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#731]
### Issue Type

Bug

### Source

source

### Giskard Library Version

1.7.0

### Giskard Server Version

1.3.2

### OS Platform and Distribution

both mac and linux

### Python version

3.10

### Installed python packages

tensorlfow==2.9.2

### Current Behaviour?

```shell
Traceback (most recent call last):
  File "/Users/rak/Documents/giskard-master/python-client/.venv/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 702, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/Users/rak/Documents/giskard-master/python-client/.venv/lib/python3.10/site-packages/google/protobuf/internal/type_checkers.py", line 126, in CheckValue
    raise TypeError(message)
TypeError: False has type <class 'numpy.bool_'>, but expected one of: (<class 'bool'>, <class 'numbers.Integral'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rak/Documents/giskard-master/python-client/.venv/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/Users/rak/Documents/giskard-master/python-client/.venv/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 704, in field_setter
    raise TypeError(
TypeError: Cannot set worker.SingleTestResult.passed to False: False has type <class 'numpy.bool_'>, but expected one of: (<class 'bool'>, <class 'numbers.Integral'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rak/Documents/giskard-master/python-client/giskard/ml_worker/utils/error_interceptor.py", line 48, in wrapper
    res = await loop.run_in_executor(pool, behavior, request, context)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/rak/Documents/giskard-master/python-client/giskard/ml_worker/server/ml_worker_service.py", line 146, in runTest
    exec(request.code, _globals)
  File "<string>", line 26, in <module>
  File "/Users/rak/Documents/giskard-master/python-client/giskard/ml_worker/testing/performance_tests.py", line 428, in test_diff_precision
    return self._test_diff_prediction(
  File "/Users/rak/Documents/giskard-master/python-client/giskard/ml_worker/testing/performance_tests.py", line 301, in _test_diff_prediction
    metric_1 = test_fn(reference_slice, model).metric
  File "/Users/rak/Documents/giskard-master/python-client/giskard/ml_worker/testing/performance_tests.py", line 195, in test_precision
    return self._test_classification_score(precision_score, actual_slice, model, threshold)
  File "/Users/rak/Documents/giskard-master/python-client/giskard/ml_worker/testing/performance_tests.py", line 87, in _test_classification_score
    SingleTestResult(
  File "/Users/rak/Documents/giskard-master/python-client/.venv/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 560, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/Users/rak/Documents/giskard-master/python-client/.venv/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 477, in _ReraiseTypeErrorWithFieldName
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/rak/Documents/giskard-master/python-client/.venv/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/Users/rak/Documents/giskard-master/python-client/.venv/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 704, in field_setter
    raise TypeError(
TypeError: Cannot set worker.SingleTestResult.passed to False: False has type <class 'numpy.bool_'>, but expected one of: (<class 'bool'>, <class 'numbers.Integral'>) for field SingleTestResult.passed
×
```

### Standalone code OR list down the steps to reproduce the issue

```shell
- upload the Text_classification_Using_Tensorflow_Neural_Network.ipynb model
- run all the automatic test
- all will fail with the error above except: 
  - Right label
  - Classification Probability in Range
  - Custom Test
```

**Comment by andreybavt** [comment]
@rabah-khalek which version of tensorflow were you using? I'm having issues serializing the TF model from this notebook

**Comment by rabah-khalek** [comment]
Yes, I left a note back then in the manual test plan: tensorflow == 2.9.2
tensorflow 2.11.0 won’t work.

**Comment by andreybavt** [comment]
Weird, I didn't manage to reproduce with the following python 3.10.8 conda environment:

[env.txt](https://github.com/Giskard-AI/giskard/files/10698372/env.txt)


<img width="1565" alt="image" src="https://user-images.githubusercontent.com/7889985/217845505-cbd09bcb-fb72-409a-8408-7437c60599bd.png">


@rabah-khalek , could you maybe attach your `pip freeze` too?

**Comment by rabah-khalek** [comment]
this is the same test that you did. I will refresh my installation of my python3.10 env. 
<img width="1672" alt="Screenshot 2023-02-09 at 15 54 37" src="https://user-images.githubusercontent.com/32709181/217847568-6ba5d332-fd5d-4964-8240-cb7739e8c4b5.png">

**Comment by rabah-khalek** [comment]
I tried installing these libraries one by one and reporfmed the test but I couldn't reproduce the issue:
```
pip install transformers==4.26.0
pip install tweepy
pip install responses==0.18.0
pip install torch==1.13.1
```
I suggest closing it for now, until we can reproduce it again.
