### ISSUE TITLE
[GSK-826] Cannot load model with internal ML worker

### ISSUE THREAD

**Issue by kevinmessiaen** [Giskard-AI/giskard#828]
Branch: [https://github.com/Giskard-AI/giskard/tree/feature/ai-test-v2](https://github.com/Giskard-AI/giskard/tree/feature/ai-test-v2)

# Issue:

When using internal ML worker, the load method try to read the cache folder, however it is empty due to not having a `GiskardClient` to load the artifact

# Logs

```
2023-02-16 15:06:52,088 pid:1003 MainThread giskard.ml_worker.utils.error_interceptor ERROR    Cannot find existing model credit.93112387-7bce-4b71-826e-933cfb235a65 in /Users/kevinmessiaen/giskard-home/cache/credit/models/93112387-7bce-4b71-826e-933cfb235a65
Traceback (most recent call last):
  File "/Users/kevinmessiaen/work/giskard/python-client/giskard/ml_worker/utils/error_interceptor.py", line 49, in wrapper
    res = await loop.run_in_executor(pool, behavior, request, context)
  File "/usr/local/Cellar/python@3.7/3.7.16/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/kevinmessiaen/work/giskard/python-client/giskard/ml_worker/server/ml_worker_service.py", line 144, in runTestSuite
    global_arguments = self.parse_test_arguments(request.globalArguments)
  File "/Users/kevinmessiaen/work/giskard/python-client/giskard/ml_worker/server/ml_worker_service.py", line 173, in parse_test_arguments
    value = Model.download(self.client, arg.model.project_key, arg.model.id)
  File "/Users/kevinmessiaen/work/giskard/python-client/giskard/core/model.py", line 214, in download
    assert local_dir.exists(), f"Cannot find existing model {project_key}.{model_id} in {local_dir}"
```

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-826](https://linear.app/giskard/issue/GSK-826/cannot-load-model-with-internal-ml-worker)</sub>

**Comment by andreybavt** [comment]
To fix start internal ML Worker with`GSK_CACHE_DIR=projects`
