### ISSUE TITLE
[GSK-835] Add support for large datasets

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#839]
Currently, in case of inspection of a large dataset if a response is too large there's an error:

```
2023-02-22 18:39:49.029 ERROR 11510 --- [  XNIO-1 task-4] a.g.w.r.c.InspectionController           : Exception in createInspection() with cause = 'ai.giskard.exception.MLWorkerException' and exception = 'RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 40063058'

io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 40063058
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at ai.giskard.worker.MLWorkerGrpc$MLWorkerBlockingStub.runModel(MLWorkerGrpc.java:768)
	at ai.giskard.service.ModelService.predictSerializedDataset(ModelService.java:133)
```

to reproduce:

```
    client = GiskardClient("http://localhost:9000", "...")
    german_credit_data.meta.name = 'big_data'
    german_credit_data.df = pd.concat([german_credit_data.df]*500)
    
    german_credit_model.meta.name = 'my model'
    german_credit_model.upload(client, 'credit')
    german_credit_data.save(client, 'credit')
```

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-835](https://linear.app/giskard/issue/GSK-835/add-support-for-large-datasets)</sub>

**Comment by andreybavt** [comment]
with sampling and dataset upload through http this is less of an issue
